config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'pages/:id/edit_text' => 'pages#edit_text'

  resources :original_texts
  resources :cards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'original_texts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :original_texts

end

app/models/original_text.rb
class OriginalText < ApplicationRecord
  belongs_to :card
  has_many :pages

end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :original_text

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :title_kana)
    end
end

app/controllers/original_texts_controller.rb
class OriginalTextsController < ApplicationController
  before_action :set_original_text, only: [:show, :edit, :update, :destroy]

  # GET /original_texts
  # GET /original_texts.json
  def index
    @original_texts = OriginalText.all
  end

  # GET /original_texts/1
  # GET /original_texts/1.json
  def show
  end

  # GET /original_texts/new
  def new
    @original_text = OriginalText.new
  end

  # GET /original_texts/1/edit
  def edit
  end

  # POST /original_texts
  # POST /original_texts.json
  def create
    @original_text = OriginalText.new(original_text_params)

    respond_to do |format|
      if @original_text.save
        format.html { redirect_to @original_text, notice: 'Original text was successfully created.' }
        format.json { render :show, status: :created, location: @original_text }
      else
        format.html { render :new }
        format.json { render json: @original_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /original_texts/1
  # PATCH/PUT /original_texts/1.json
  def update
    respond_to do |format|
      if @original_text.update(original_text_params)
        format.html { redirect_to @original_text, notice: 'Original text was successfully updated.' }
        format.json { render :show, status: :ok, location: @original_text }
      else
        format.html { render :edit }
        format.json { render json: @original_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /original_texts/1
  # DELETE /original_texts/1.json
  def destroy
    @original_text.destroy
    respond_to do |format|
      format.html { redirect_to original_texts_url, notice: 'Original text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_original_text
      @original_text = OriginalText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def original_text_params
      params.require(:original_text).permit(:card_id, :book_title, :book_publisher, :book_publish_year)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :edit_text, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # GET /pages/1/edit_text
  def edit_text
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        #format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.html { redirect_to action: 'edit_text', id: @page.id, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:original_text_id, :original_image_url, :text_working)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/original_texts_helper.rb
module OriginalTextsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :title_kana %>
    <%= f.text_field :title_kana %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Title kana</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.title %></td>
        <td><%= card.title_kana %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Title kana:</strong>
  <%= @card.title_kana %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlackThunder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
          .zoomer_wrapper {
            border: 1px solid #ddd;
            border-radius: 3px;
    	height: 500px;
    	margin: 10px 0;
            overflow: hidden;
    	width: 100%;
          }
        </style>
        <script>
        $(document).ready(function() {
          $(".zoomer_basic").zoomer();
        });
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/original_texts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
<h1>底本一覧</h1>

 <div class="row">

 <% @original_texts.each do |original_text| %>
 <div class="col-sm-6 col-md-4">
  <div class="panel panel-default">

   <div class="panel-heading">
    <%= link_to original_text.book_title, original_text %>
	 </div>

   <div class="panel-body">
    <b>作品情報</b><br/>
    作品ID: <%= link_to original_text.card_id, :controller => "cards", :action => "show", :id => original_text.card_id %><br/>
    作品名: <%= link_to original_text.card.title, :controller => "cards", :action => "show", :id => original_text.card_id %><br/>
    作品名読み: <%= original_text.card.title_kana if original_text.card %><br/>
    <br/>
    <b>底本情報</b><br/>
    書籍名: <%= original_text.book_title %><br/>
    出版社名: <%= original_text.book_publisher %><br/>
    初版発行年: <%= original_text.book_publish_year %><br/>

    <button type="button" class="btn btn-default">生成</button>
    &nbsp;
    <a href="/KaisekiGairon/KaisekiGairon/review/book.pdf">pdf</a> |
    <a href="/KaisekiGairon/KaisekiGairon/review/book.epub">epub</a> |
    <a href="/KaisekiGairon/KaisekiGairon/review/webroot/index.html">xhtml</a>
	 </div>

	 <div class="panel-footer text-right">
     <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
     <%= link_to '詳細と編集へ', original_text %>
	 </div>

  </div>
 </div>
 <% end %>

 <div class="col-sm-6 col-md-4">
  <div class="panel panel-default">
   <div class="panel-heading">
    <br/>
   </div>
   <div class="panel-body text-center">
    <%= link_to '底本の新規登録', new_original_text_path %>
   </div>
   <div class="panel-footer">
    <br/>
   </div>
  </div>
 </div>

</div><%# row %>

</div><%# container-fluid %>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_text_id %>
    <%= f.number_field :original_text_id %>
  </div>

  <div class="field">
    <%= f.label :page_no %>
    <%= f.number_field :page_no %>
  </div>

  <div class="field">
    <%= f.label :original_image_url %>
    <%= f.text_field :original_image_url %>
  </div>

  <div class="field">
    <%= f.label :text_working %>
    <%= f.text_area :text_working %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_pagelist.html.erb
<% page.original_text.pages.each do |pg| %>
 <% if pg.id == page.id %>
  <%= image_tag pg.original_image_url, :width => '120' %>
 <% else %>
  <%= link_to image_tag(pg.original_image_url, :width => '120'), :action => "edit_text", :id => pg.id %>
 <% end %>
 <br/>
 <%= pg.page_no %>
 <br /><br />
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/edit_text.html.erb
<div class="container-fluid">
<h1>「<%= @page.original_text.book_title %>」 <%= @page.page_no %>頁 の編集</h1>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-2">
<%= render 'pagelist', page: @page %>
</div>

<div class="col-xs-10">
<%# 底本のビュー %>
<%# <div style="overflow:scroll; height:300px; overflow-y:scroll"> %>
<div class="zoomer_wrapper zoomer_basic">
  <%= image_tag @page.original_image_url %>
</div>

<%# 編集エリア %>
<%= form_for(@page) do |f| %>
 <div class="field">
  <%= f.text_area :text_working, :size => "100x15" %>
 </div>
 <div class="actions">
  <%= f.submit %>
 </div>
<% end %>
</div>

</div><%# container-fluid %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Original text</th>
      <th>Page No</th>
      <th>Original image url</th>
      <th>Text working</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.original_text_id %></td>
        <td><%= page.page_no %></td>
        <td><%= page.original_image_url %></td>
        <td><%= page.text_working %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original text:</strong>
  <%= @page.original_text_id %>
</p>

<p>
  <strong>Page No:</strong>
  <%= @page.page_no %>
</p>

<p>
  <strong>Original image url:</strong>
  <%= @page.original_image_url %>
</p>

<p>
  <strong>Text working:</strong>
  <%= @page.text_working %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/shows/_form.html.erb
<%= form_for(original_text) do |f| %>
  <% if original_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(original_text.errors.count, "error") %> prohibited this original_text from being saved:</h2>

      <ul>
      <% original_text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_id %>
    <%= f.number_field :card_id %>
  </div>

  <div class="field">
    <%= f.label :book_title %>
    <%= f.text_field :book_title %>
  </div>

  <div class="field">
    <%= f.label :book_publisher %>
    <%= f.text_field :book_publisher %>
  </div>

  <div class="field">
    <%= f.label :book_publish_year %>
    <%= f.text_field :book_publish_year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Original Text</h1>

<%= render 'form', original_text: @original_text %>

<%= link_to 'Show', @original_text %> |
<%= link_to 'Back', original_texts_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
<h1>底本一覧</h1>

 <div class="row">

 <% @original_texts.each do |original_text| %>
 <div class="col-sm-6 col-md-4">
  <div class="panel panel-default">

   <div class="panel-heading">
    <%= link_to original_text.book_title, original_text %>
	 </div>

   <div class="panel-body">
    <b>作品情報</b><br/>
    作品ID: <%= link_to original_text.card_id, :controller => "cards", :action => "show", :id => original_text.card_id %><br/>
    作品名: <%= link_to original_text.card.title, :controller => "cards", :action => "show", :id => original_text.card_id %><br/>
    作品名読み: <%= original_text.card.title_kana if original_text.card %><br/>
    <br/>
    <b>底本情報</b><br/>
    書籍名: <%= original_text.book_title %><br/>
    出版社名: <%= original_text.book_publisher %><br/>
    初版発行年: <%= original_text.book_publish_year %><br/>
	 </div>

	 <div class="panel-footer text-right">
     <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
     <%= link_to '詳細と編集へ', original_text %>
	 </div>

  </div>
 </div>
 <% end %>

 <div class="col-sm-6 col-md-4">
  <div class="panel panel-default">
   <div class="panel-heading">
    <br/>
   </div>
   <div class="panel-body text-center">
    <%= link_to '底本の新規登録', new_original_text_path %>
   </div>
   <div class="panel-footer">
    <br/>
   </div>
  </div>
 </div>

</div><%# row %>

</div><%# container-fluid %>

app/views/shows/new.html.erb
<h1>New Original Text</h1>

<%= render 'form', original_text: @original_text %>

<%= link_to 'Back', original_texts_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

<h1><%= @original_text.book_title %></h1>

<p>
  <strong>Card:</strong>
  <%= @original_text.card_id %>: <%= link_to @original_text.card.title, :controller => "cards", :action => "show", :id => @original_text.card_id %>
</p>

<p>
  <strong>Book title:</strong>
  <%= @original_text.book_title %>
</p>

<p>
  <strong>Book publisher:</strong>
  <%= @original_text.book_publisher %>
</p>

<p>
  <strong>Book publish year:</strong>
  <%= @original_text.book_publish_year %>
</p>

<p>
  <strong>Page list:</strong>
  <ul>
  <% @original_text.pages.each do |pg| %>
   <li><%= link_to pg.page_no, :controller => "pages", :action => "show", :id => pg.id %>: <%= pg.original_image_url %>
    [<%= link_to "編集", :controller => "pages", :action => "edit_text", :id => pg.id %>]
  <% end %>
</ul>
</p>

<%= link_to '編集へ', edit_original_text_path(@original_text) %> |
<%= link_to '底本一覧へ', original_texts_path %>

</div><%# container-fluid %>